name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy-website:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: yarn install

      - name: Build Pages
        run: yarn build
        env:
          MICRO_CMS_API_KEY: ${{ secrets.MICRO_CMS_API_KEY }}

      - name: Add nojekyll
        run: touch ./_site/.nojekyll

      - name: deploy
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site
